frontend/index.html
frontend/src/components/Navbar/index.jsx
frontend/src/context/ThemeContext.jsx
frontend/src/index.css

Added Pallete for light and dark mode

Color Pallette done

---

frontend/src/App.jsx
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/Login/index.jsx
frontend/src/pages/Register/index.jsx
frontend/src/pages/UserProfile/index.jsx

added User profile, dashboard, login, register

Added Routes to work with

---

backend/app/routes/auth.py

Se creo el Endpoint para registrar a los usuarios en la aplicacion con las validacione pertinentes

AC-55 task, done: Register Endpoint succesfully created

---

backend/app/__init__.py
backend/app/models/user.py
backend/app/routes/auth.py

1. Endpoint para el Login del usuario con JWT implementado
2. Correcion para el uso de Variables de Entorno en el `__init__.py`
3. Actualizacion del metodo `user.to_didct()` . Devolvia el timestamps, lo cual no es necesario en el frontend
4. Inicialmente tambien quite el ID del metodo del usuario, lo cual a la larga treaeria problemas ya que el frontend necesitara ese ID. Error corregido

AC-56 Task Done: Login Endpoint succesfully created

---

backend/app/__init__.py
backend/app/config.py
backend/app/models/user.py
backend/app/routes/auth.py
backend/app/routes/users.py
backend/app/schemas/user_schema.py

1. Creacion de CRUD de usuarios (Read, Update)
2. Creacion de Schema de Validacion para Update
3. Endpoints de Usuarios Protegidos por JWT y Por roles
4. Logica de endpoints para que el usaurios solo pueda acceder a su propia informacion y actualizar unicamente esta
5. Creacion del metodo `isModerator` en el modelo de Usuario
6. Reorganizacion de la estructura base de la App => Creacion de un archivo `config.py` que exporta las variables de entorno y la `API_PREFIX`

AC-57 Task Done: Users CRUD successfully implemented with JWT and Roles

---

backend/app/__init__.py
backend/app/routes/tags.py
frontend/index.html
frontend/src/components/Dashboard/index.jsx

Connected Front with db without JWT requirements

Tags from DB without JWT

---

backend/app/routes/hackathons.py

1. Crear Endpoint Para obtener Datos de un Hackaton en Particualr

AC-93 Task Done: Single Hackaton Endpoint Done

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/AnimatedSection/index.jsx
frontend/src/components/BenefitsComponent/index.jsx
frontend/src/components/BentoGridSection/index.jsx
frontend/src/components/Hero/index.jsx
frontend/src/components/TechGrid/index.jsx
frontend/src/components/Testimonials/index.jsx

1. Implementacion de Animaciones para las secciones de la Landin Page usando Framer Motion

AC-96 Task Done: Landing Animations with Framer

---

backend/app/config.py
frontend/src/context/AuthContext.jsx
frontend/src/pages/Register/index.jsx
frontend/src/services/index.js

1. Fomulario de registro funcionando con la APi del backend
2. Regulacion de la duracion del token a 1hr

AC-26 Task Done: Frontend User Register Fully implemented

---

frontend/src/components/Dashboard/index.jsx
frontend/src/components/DashboardCards/index.jsx
frontend/src/components/HackathonsTable/index.jsx
frontend/src/components/Navbar/index.jsx
frontend/src/components/TagsComponent/index.jsx

1. Implementacion Responsive del Dashboard
2. Implementacion de filtrado mediante Tags
3. Implementacion de buscado por nombre de hackathons en la tabla
4. Modificaciones visuales en componentes y animaciones leves con Framer

AC-118 Task Done: Table Search and Filtering implemented

---

frontend/src/App.jsx
frontend/src/components/Avatar/index.jsx
frontend/src/components/Dashboard/index.jsx
frontend/src/components/HackathonsCalendar/index.jsx
frontend/src/components/Layout/index.jsx
frontend/src/components/Navbar/index.jsx
frontend/src/components/Sidebar/index.jsx
frontend/src/components/TagsComponent/index.jsx

1. Creacion de Sidebar estatico
2. Refactor Ui dashboard y layout

AC-122 Task Done: Refactor Sidebar UI completed

---

backend/app/models/team.py
backend/app/routes/teams.py
frontend/src/index.css

1. Creacion de ruta para obtener solicitudeds asociadas a mi
2. Integraciond e solicitudes en el modelo de Hackathon para cada equipo

AC-123 Task Done: Requests added to Hackathons Model, and new Route

---

backend/.env.example
backend/app/__init__.py
frontend/.env.example
frontend/src/services/index.js

Main branch fixed

---

frontend/src/components/TeamComponent/index.jsx
frontend/src/services/index.js
frontend/src/utilities/userUtils.js

Arreglado logica de solicitudes y renderizado en Teams view

AC-151 Task done

---

frontend/src/pages/LeaderboardPage/index..jsx

1. Bug de posiciones en el LeaderBoard page arreglado
2. Animaciones de entrada y busqueda
3. Resultado de no encontrado  implementado para busquedas que no coinciden

AC-31 Task Done: Leaderboard Bug fixed, Animations and not found result

---

backend/app/routes/users.py
frontend/src/App.jsx
frontend/src/components/Avatar/index.jsx
frontend/src/components/HackathonsHistory/index.jsx
frontend/src/components/LikesSection/index.jsx
frontend/src/components/Sidebar/index.jsx
frontend/src/components/UserProfile/index.jsx
frontend/src/context/AppContext.jsx
frontend/src/pages/LeaderboardPage/index..jsx
frontend/src/services/index.js

1. Perfil de Usuario actualizado y modificado para mostrar perfil en base a 1 ID

AC-153 Task Done: UserProfile updated

---

frontend/src/App.jsx
frontend/src/components/PrivateRoute/index.jsx
frontend/src/components/ScrollToTop/index.jsx
frontend/src/components/SpinnerLoader/index.jsx
frontend/src/components/UserProfile/index.jsx
frontend/src/context/AuthContext.jsx

1. Crear componente que resete el scrollbar al navegar a otra pestaña
2. Solventar redireccion al dashboard al recargar la pagina mediante un loadingState

A-157 and AC-155 Tasks Done

---

frontend/.env.example
frontend/src/components/Dashboard/index.jsx
frontend/src/components/HackathonComponent/index.jsx
frontend/src/components/HackathonsCalendar/index.jsx
frontend/src/components/Layout/index.jsx
frontend/src/components/Sidebar/index.jsx
frontend/src/services/index.js
frontend/src/utilities/dateUtils.js

1. Correcion de bug de calendario de fechas en el dashboard.
2. Correcion de util de fecha para evitar conflictos de zona horaria
3. Correcion de vista de hackathon con respecto a fecha de inicio
4. Modificar ubicacion del chatbot al layout para que persista en todas las vistas
5. Implementacion de variables de entorno para el chatbot para mayor seguridad

AC-156 Task Done: Calendar and Date Bugs fixed

---

frontend/src/services/index.js

1. Actualizacion de Prompt de chatbot para restringir completaciones de codigo y darle contexto general de la aplicacion para que tenga conocimiento de que responder

Chatbot Initial Prompt Updated

---

backend/app/routes/hackathons.py
backend/app/routes/teams.py
frontend/src/components/CardComponent/index.jsx
frontend/src/components/CreateTeamModal/index.jsx
frontend/src/components/EditHackathonModal/index.jsx
frontend/src/components/EvaluationModal/index.jsx
frontend/src/components/HackathonComponent/index.jsx
frontend/src/components/JudgesModal/index.jsx
frontend/src/components/JudgesReview/index.jsx
frontend/src/components/RatingStars/index.jsx
frontend/src/components/StaticStars/index.jsx
frontend/src/components/TeamComponent/index.jsx
frontend/src/components/TeamsModal/index.jsx
frontend/src/components/TestimonialCarrousel/index.jsx
frontend/src/components/warningmodal/index.jsx
frontend/src/context/AppContext.jsx
frontend/src/services/index.js

-Leaderboard de ganadores en hackathons individuales (SOLO cuando el hackathon es "finished" si es closed no interactua)
-Jueces puntuando con rating bar (con medias estrellas) y feedback de su puntaje
-Jueces capaces de votar 1 SOLA vez por equipo (luego se deshabilita el boton, no se puede volver a votar ni editar)
-Moderadores  pueden dar como finalizado o cancelar un hackathon 
-Vista de comentarios de feedback de parte de los jueces a los equipos (Solo visibles una vez se acabe el hackathon, en caso de cancelado no se muestran)
-Arreglado  Problema de fechas en edicion de hackathon (Permite como fecha de inicio el dia actual, no acepta fechas pasadas)
-Creado contexto de AllWinners
-Creado contexto de AlScores
-Creado rutas de back para ganadores y scores
-Creado services para …

AC-160 AC-45 AC-115 AC-43 AC-154 AC-151 ALL TASK DONE

---

frontend/src/pages/LeaderboardPage/index..jsx

1. Agregar Debouncer  a vista de leaderboard page
PD: intente modificar par reutilizar el componente, pero no me funciona por mas que lo intente con la paginacion de la vista, por ende aplique el debouncer directamente con la libreria en la pagina

AC-187 Task Done: Debouncer in leaderboard Page

---

backend/app/routes/notifications.py

Final test para notificaciones leidas

Final Notification test

---

backend/app/routes/notifications.py

Final Notification test v2
